import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEST = join(__dirname, '../src/lib/ai/modules/narrative-intake/signal-classifier.ts');

// ---- build content from safe string segments ----
const L = '\n';
const parts = [];
const a = (s) => parts.push(s + L);

a("import type {");
a("  UsableSignalDecision,");
a("  SignalType,");
a("  SignalStrength,");
a("  UsableSignalReasonCode,");
a("  IntakeSourceProvenanceRef,");
a("  IntakeDecisionMeta,");
a("} from '@/types/intake';");
a("");
a("export const SIGNAL_CLASSIFIER_VERSION = 'v1' as const;");
a("");
a("const SELF_CORRECTION_PATTERNS = [");
a("  /i (got it|handled it|approached it) wrong/i,");
a("  /i made a mistake/i,");
a("  /i mishandled/i,");
a("  /i reacted (badly|poorly)/i,");
a("  /my first instinct was wrong/i,");
a("  /i initially handled/i,");
a("  /i (was corrected|was called out|got feedback)/i,");
a("  /someone (told me|challenged me|pointed out)/i,");
a("  /after (feedback|being told|someone said)/i,");
a("  /i changed (my approach|how i)/i,");
a("  /i adapted my approach/i,");
a("  /i responded differently/i,");
a("  /i adjusted/i,");
a("  /the next time i/i,");
a("  // Named-role feedback");
a("  /\\b(a|my|the)\\s+\\w+\\s+(told me|asked me|showed me|informed me|pointed out to me)\\b/i,");
a("  /i was doing the opposite\\b/i,");
a("  /i had not (been|taught|shown|shared|told|helped|included)\\b/i,");
a("  /i (rewrote|rebuilt|redesigned|reorganized|reworked|restructured) (the|my|our|a)\\b/i,");
a("];");
a("");
a("const IDENTITY_SHIFT_PATTERNS = [");
a("  /i (realized|understood) (that )?(i had been|my role|who i was)/i,");
a("  /i thought i was/i,");
a("  /i saw myself differently/i,");
a("  /my understanding of (my role|myself|what i was doing) changed/i,");
a("  /i had been (wrong about|mistaken about|treating)/i,");
a("  /that changed how i saw (myself|my job|my role)/i,");
a("  /i was not (who|what) i thought/i,");
a("];");
a("");
a("const RESPONSIBILITY_SHIFT_PATTERNS = [");
a("  /i (realized|noticed) (that )?i (had been|was) (removing|excluding|not including)/i,");
a("  /solving (it|the problem) alone (was|started)/i,");
a("  /i had been (making|taking) decisions (without|alone|by myself)/i,");
a("  /i brought (the team|everyone|others) in/i,");
a("  /i stopped (doing it|solving it) alone/i,");
a("  /i (asked for|invited|included) (help|others|the team)/i,");
a("  /i (was not|wasn.t) letting (others|them|the team)/i,");
a("  /i (advocated|fought|pushed|stood up|spoke up) for (myself|my own|my (own )?placement)\\b/i,");
a("  /i (refused to leave|stayed until|sat outside)\\b/i,");
a("  /i (wrote|created|drafted) a (document|letter|one-page|note|formal)\\b/i,");
a("  /i (waited|sat|stayed) (outside|in front of|at|near|by)\\s+the\\b/i,");
a("];");
a("");
a("const CONFLICT_REFRAME_PATTERNS = [");
a("  /conflict/i,");
a("  /disagreement/i,");
a("  /argument/i,");
a("  /tension/i,");
a("  /we (clashed|disagreed|argued)/i,");
a("  /the other (person|team|side)/i,");
a("  /after the (round|match|meeting|conversation)/i,");
a("  /i (changed|shifted) my (approach|perspective) (to|toward|about) (the conflict|the disagreement|them)/i,");
a("];");
a("");
a("const FAILURE_REINTERPRETATION_PATTERNS = [");
a("  /the (data|result|experiment|project) (was|showed|revealed) (wrong|flat|failed|unexpected)/i,");
a("  /my hypothesis was wrong/i,");
a("  /the failure (taught|showed|revealed)/i,");
a("  /if (the first attempt|it) had (worked|succeeded)/i,");
a("  /the mistake (was|became) the (condition|thing) that/i,");
a("  /i (redesigned|rebuilt|restarted)/i,");
a("  /i (never would have found|would have missed)/i,");
a("  /i (built|created|designed|wrote|developed) a (drill|system|method|process|approach|practice)\\b/i,");
a("  /\\w+\\s+students?\\s+(at|in|from) my (school|class|program|team) (now use|use|adopted|started using)\\b/i,");
a("  /all of them required (me to|switching|a)\\b/i,");
a("  /i looked at every .{0,40}(i missed|that failed|that was wrong)/i,");
a("];");
a("");
a("const SCENE_DETAIL_PATTERNS = [");
a("  /\\bwhen\\b/i,");
a("  /\\bafter\\b/i,");
a("  /\\bduring\\b/i,");
a("  /that (moment|day|session|round|shift|conversation)/i,");
a("  /my (coach|mentor|teacher|partner|teammate|patient|customer|director|advisor|counselor|librarian|principal|colleague|manager|boss) (said|told|asked|pulled|called|showed|sent|gave)\\b/i,");
a("  /\\b(a|the)\\s+(coach|mentor|teacher|nurse|advisor|counselor|parent|librarian|principal|colleague|manager|boss|director) (told|asked|said|showed|pulled|called)\\b/i,");
a("  /i said/i,");
a("  /i did/i,");
a("  /the (match|round|call|rehearsal|shift|experiment|clinic|session|tournament)/i,");
a("  /room \\d+/i,");
a("  /asked (me|for me) by name/i,");
a("];");
a("");
a("const RESUME_LIST_PATTERNS = [");
a("  /^[A-Z][^.]{2,40}(,\\s*[A-Z][^.]{2,40}){2,}/,");
a("  /captain|treasurer|president|honor roll/i,");
a("  /strong communicator|team player|hard worker/i,");
a("  /\\bAP \\w+/i,");
a("  /varsity|club|member|officer/i,");
a("];");
a("");
a("const ABSTRACT_VALUES_PATTERNS = [");
a("  /values (and|or) future direction/i,");
a("  /demonstrates? (leadership|growth|maturity|resilience)/i,");
a("  /i have always been passionate/i,");
a("  /throughout my (high school career|years)/i,");
a("  /i am (committed|dedicated|proud)/i,");
a("  /admissions committees/i,");
a("  /who i am as a person/i,");
a("  /connect .* values/i,");
a("];");
a("");
a("function countHits(text: string, patterns: RegExp[]): number {");
a("  return patterns.filter((p) => p.test(text)).length;");
a("}");
a("");
a("function allText(entries: Array<{ id: string; title: string; text: string }>): string {");
a("  return entries.map((e) => `${e.title} ${e.text}`).join(' ');");
a("}");
a("");
a("function detectSignalTypes(");
a("  text: string");
a("): { types: SignalType[]; maxHits: number } {");
a("  const candidates: Array<{ type: SignalType; hits: number }> = [");
a("    { type: 'self_correction_arc',    hits: countHits(text, SELF_CORRECTION_PATTERNS) },");
a("    { type: 'identity_shift',         hits: countHits(text, IDENTITY_SHIFT_PATTERNS) },");
a("    { type: 'responsibility_shift',   hits: countHits(text, RESPONSIBILITY_SHIFT_PATTERNS) },");
a("    { type: 'conflict_reframe',       hits: countHits(text, CONFLICT_REFRAME_PATTERNS) },");
a("    { type: 'failure_reinterpretation', hits: countHits(text, FAILURE_REINTERPRETATION_PATTERNS) },");
a("  ];");
a("  const active = candidates.filter((c) => c.hits >= 1);");
a("  const maxHits = active.length > 0 ? Math.max(...active.map((c) => c.hits)) : 0;");
a("  const types: SignalType[] = active.length > 0");
a("    ? active.sort((a, b) => b.hits - a.hits).map((c) => c.type)");
a("    : ['unknown'];");
a("  return { types, maxHits };");
a("}");
a("");
a("function inferStrength(");
a("  scenHits: number,");
a("  signalHits: number,");
a("  resumeHits: number,");
a("  abstractHits: number");
a("): SignalStrength {");
a("  if (resumeHits >= 3 || (signalHits === 0 && scenHits === 0)) return 'none';");
a("  if (abstractHits >= 3 && signalHits < 2) return 'none';");
a("  if (signalHits >= 4 && scenHits >= 3) return 'high';");
a("  if (signalHits >= 2 && scenHits >= 1) return 'medium';");
a("  if (signalHits >= 1 || scenHits >= 2) return 'low';");
a("  return 'none';");
a("}");
a("");
a("function buildReasonCodes(");
a("  types: SignalType[],");
a("  strength: SignalStrength,");
a("  resumeHits: number,");
a("  abstractHits: number,");
a("  scenHits: number");
a("): UsableSignalReasonCode[] {");
a("  const codes: UsableSignalReasonCode[] = [];");
a("  if (strength === 'none' && resumeHits >= 3) codes.push('RESUME_LIST_ONLY');");
a("  if (strength === 'none' && abstractHits >= 3) codes.push('ABSTRACT_VALUES_NO_SCENE');");
a("  if (strength === 'none' && resumeHits < 3 && abstractHits < 3) codes.push('NO_SIGNAL_DETECTED');");
a("  if (types.includes('self_correction_arc') && strength === 'high') codes.push('STRONG_SELF_CORRECTION_PRESENT');");
a("  if (types.includes('identity_shift')) codes.push('CLEAR_IDENTITY_SHIFT_PRESENT');");
a("  if (types.includes('responsibility_shift')) codes.push('RESPONSIBILITY_SHIFT_DETECTED');");
a("  if (types.includes('conflict_reframe')) codes.push('CONFLICT_REFRAME_DETECTED');");
a("  if (types.includes('failure_reinterpretation')) codes.push('FAILURE_REINTERPRETATION_DETECTED');");
a("  if (scenHits >= 3) codes.push('SCENE_DETAIL_SUFFICIENT');");
a("  if (strength === 'low') codes.push('AMBIGUOUS_POSSIBLE_SIGNAL');");
a("  return codes.length > 0 ? codes : ['NO_SIGNAL_DETECTED'];");
a("}");
a("");
a("export interface SignalClassifierInput {");
a("  story_entries: Array<{");
a("    id: string;");
a("    title: string;");
a("    text: string;");
a("  }>;");
a("  draft_text: string | null;");
a("  session_id: string;");
a("}");
a("");
a("export function classifyUsableSignal(");
a("  input: SignalClassifierInput");
a("): UsableSignalDecision {");
a("  const storyText = allText(input.story_entries);");
a("  const draftText = input.draft_text ?? '';");
a("  const combinedText = `${storyText} ${draftText}`.trim();");
a("  const { types, maxHits } = detectSignalTypes(combinedText);");
a("  const scenHits = countHits(storyText, SCENE_DETAIL_PATTERNS);");
a("  const resumeHits = countHits(combinedText, RESUME_LIST_PATTERNS);");
a("  const abstractHits = countHits(draftText, ABSTRACT_VALUES_PATTERNS);");
a("  const strength = inferStrength(scenHits, maxHits, resumeHits, abstractHits);");
a("  const usable = strength !== 'none';");
a("  const confidence: 'high' | 'medium' | 'low' =");
a("    strength === 'high' ? 'high' :");
a("    strength === 'medium' ? 'medium' :");
a("    strength === 'low' ? 'low' : 'high';");
a("  const reason_codes = buildReasonCodes(types, strength, resumeHits, abstractHits, scenHits);");
a("  const evidence_sources: IntakeSourceProvenanceRef[] = input.story_entries.map((e) => ({");
a("    source_id: e.id,");
a("    source_type: 'story_entry' as const,");
a("    excerpt: e.text.slice(0, 120),");
a("  }));");
a("  const meta: IntakeDecisionMeta = {");
a("    decision_version: SIGNAL_CLASSIFIER_VERSION,");
a("    taxonomy_version: 'taxonomy_v1',");
a("    made_at: new Date().toISOString(),");
a("    made_by: 'classifier',");
a("  };");
a("  return {");
a("    usable_signal: usable,");
a("    signal_strength: strength,");
a("    signal_types: types,");
a("    confidence,");
a("    reason_codes,");
a("    evidence_sources,");
a("    meta,");
a("  };");
a("}");

writeFileSync(DEST, parts.join(''), 'utf8');
console.log('OK wrote', DEST);