from pathlib import Path

p = Path('/Volumes/TOSHIBA EXT/College Essay/src/lib/fm/direction.ts')
text = p.read_text()
repls = [
    ("return hasClaimFirstForm(direction) && directionHasCore && directionWordCount <= 34 && whyHasBecause && nextHasConcrete;", "return hasClaimFirstForm(direction) && directionHasCore && directionWordCount <= 50 && whyHasBecause && nextHasConcrete;"),
    ("    'Choose this over the weaker version because',\n    'This beats the alternate read because',\n    'Pick this direction because',\n    'This is stronger than the fallback because',\n    'Compared with the weaker path, this works because',\n    'From a drafting lens, choose this because',\n    'This is the clearer coaching path because',\n    'If your goal is a writable claim, pick this because',", "    'This is stronger than the obvious version because',\n    'This beats the alternate read because',\n    'Rather than the flatter version, choose this because',\n    'This is stronger than the fallback because',\n    'Compared with the weaker path, this works because',\n    'This beats the hollow version because',\n    'Rather than staying vague, use this because',\n    'This is stronger as a drafting claim because',"),
    ("function ensureConcreteNextMove(nextMove: string, seedValue = 0): string {", "function ensureWhyValidatorContract(why: string, seedValue = 0): string {\n  let normalized = ensureComparativeWhy(why, seedValue);\n\n  if (!hasComparativeWhySignal(normalized)) {\n    const body = normalized.charAt(0).toLowerCase() + normalized.slice(1);\n    normalized = `This beats the weaker read because ${body}`;\n  }\n\n  if (!hasDraftingPayoffSignal(normalized)) {\n    const payoffVariants = [\n      'Drafting payoff: start with one scene, then write claim and immediate consequence.',\n      'Drafting payoff: write 3 lines — moment, decision, result.',\n      'Drafting payoff: this gives you a clear opening paragraph order.',\n    ] as const;\n    const addOn = payoffVariants[(stableTextHash(normalized) + seedValue) % payoffVariants.length];\n    normalized = `${normalized} ${addOn}`;\n  }\n\n  return normalizeSentence(normalized);\n}\n\nfunction ensureConcreteNextMove(nextMove: string, seedValue = 0): string {"),
    ("? `Center your essay on the claim that ${turningQ} made responsibility your call, and your next action proved it.`\n          : 'Center your essay on the claim that responsibility became your call, then show the next action that proved it.';", "? `Make your main claim that ${turningQ} made responsibility your call, and your next action proved it.`\n          : 'Make your main claim that responsibility became your call, then show the next action that proved it.';"),
    ("why_this_direction: ensureComparativeWhy(why_this_direction, seedValue),", "why_this_direction: ensureWhyValidatorContract(why_this_direction, seedValue),"),
    ("? `Center your essay on the method you rebuilt after ${turningQ}: what you changed and how ${consequenceQ} proved it held.`\n      : turningQ\n        ? `Center your essay on what ${turningQ} exposed in your approach, what you changed, and the first result that proved it worked.`\n        : `Center your essay on one breakdown, the method you rebuilt, and the first result that proved the new approach held.`,", "? `Argue that the method you rebuilt after ${turningQ} changed your standard, and show how ${consequenceQ} proved it held.`\n      : turningQ\n        ? `Argue that ${turningQ} exposed a flaw in your approach, then show what you changed and the first result that proved it worked.`\n        : `Argue that one breakdown forced a rebuilt method, then show the first result that proved the new approach held.`,"),
    ("turningQ\n      ? `Center your essay on the moment what you believed about yourself collided with what ${turningQ} proved.`\n      : 'Center your essay on where your self-image conflicted with what the moment required.',", "turningQ\n      ? `Argue that what you believed about yourself collided with what ${turningQ} proved, and show the standard that replaced it.`\n      : 'Argue that your self-image conflicted with what the moment required, and show the decision standard that replaced it.',"),
    ("    'essay_about_restate_fail',\n    'comprehension_fail',\n  ]);", "    'essay_about_restate_fail',\n  ]);"),
    ("  const strictSurvivors = shellSafeEligible.filter((candidate) => candidate.rejection_reasons.length < 2);\n  const rankedSource = strictSurvivors.length >= 2\n    ? strictSurvivors\n    : (shellSafeEligible.length > 0 ? shellSafeEligible : (vetoEligible.length > 0 ? vetoEligible : scoredAdjusted));", "  const strictSurvivors = shellSafeEligible.filter((candidate) => candidate.rejection_reasons.length < 2);\n  const rankedSourceBase = strictSurvivors.length >= 2\n    ? strictSurvivors\n    : (shellSafeEligible.length > 0 ? shellSafeEligible : (vetoEligible.length > 0 ? vetoEligible : scoredAdjusted));\n\n  const MIN_VIABLE_SURVIVORS = 3;\n  const hardFailCount = (candidate: RankedRuntimeDirectionCandidate): number =>\n    candidate.rejection_reasons.filter((r) => hardFailReasons.has(r)).length;\n  const shellFailCount = (candidate: RankedRuntimeDirectionCandidate): number =>\n    candidate.rejection_reasons.filter((r) => shellHardFailReasons.has(r)).length;\n\n  const rankedSource = [...rankedSourceBase];\n  if (rankedSource.length < MIN_VIABLE_SURVIVORS) {\n    const currentIds = new Set(rankedSource.map((c) => c.candidate_id));\n    const backfillPool = scoredAdjusted\n      .filter((candidate) => !currentIds.has(candidate.candidate_id))\n      .sort((a, b) => {\n        const hardDelta = hardFailCount(a) - hardFailCount(b);\n        if (hardDelta != 0) return hardDelta;\n        const shellDelta = shellFailCount(a) - shellFailCount(b);\n        if (shellDelta != 0) return shellDelta;\n        const scoreDelta = b.scores.total_score - a.scores.total_score;\n        if (abs(scoreDelta) > 0.001) return 1 if scoreDelta > 0 else -1;\n        return 1 if b.scores.directional_usefulness > a.scores.directional_usefulness else -1;\n      });\n\n      for (const candidate of backfillPool) {\n      if (rankedSource.length >= MIN_VIABLE_SURVIVORS) break;\n      rankedSource.push({\n        ...candidate,\n        rejection_reasons: candidate.rejection_reasons.includes('pool_backfill_recovery')\n          ? candidate.rejection_reasons\n          : [...candidate.rejection_reasons, 'pool_backfill_recovery'],\n      });\n    }\n  }")
]
for old, new in repls:
    if old not in text:
        print('missing:', old[:120])
        raise SystemExit(1)
    text = text.replace(old, new, 1)
p.write_text(text)
print('patched')
